language: php

dist: bionic

sudo: false

php:  
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - 8.0
    - nightly    

jobs:
  allow_failures:
    - php: nightly

install:
    - composer update
    - vendor/bin/phpunit install

script:
    - vendor/bin/phpunit
        